import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/store/ReduxProvider";
import AppLayout from "@/components/layouts";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Review Screen - DocSumo AI",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.webp",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <AppLayout>
        {children}
        <Toaster position="top-right" richColors />
      </AppLayout>
    </ReduxProvider>
  );
}
